DEP 4.10 requirements
silverstripe/recipe-blog pull request #29
Opened 2021-11-29 02:58 UTC by emteknetnz

Issue https://github.com/silverstripeltd/product-issues/issues/492

2021-12-02 02:38 UTC, maxime-rainville requested changes

2021-12-02 02:38 UTC, maxime-rainville commented on composer.json
> +        "silverstripe/comments": "3.8.x-dev",
```suggestion
        "silverstripe/comments": "3.7.x-dev",
```

We shipped with 3.7.2

2021-12-02 02:59 UTC, emteknetnz commented on composer.json
> +        "silverstripe/comments": "3.8.x-dev",
Good catch, have updated

2021-12-03 04:38 UTC, maxime-rainville approved these changes
LGTM

2021-12-03 04:39 UTC, merged